spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bread_cloud
    username: root
    password: root
  cache:
    type: redis
    redis:
      time-to-live: 1h
  redis:
    host: 192.168.235.100
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0

bread-cloud:
  default:
    avatar: https://bread-cloud.oss-cn-beijing.aliyuncs.com/avatar/default.png
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tD4NncSDbJLcJoqx2gv
    access-key-secret: Ai1SvEM1XlVDZmiTaztc6PvC2IHBx3
    bucket-name: bread-cloud